#ifndef FRAME_PACER_HUD_VULKAN_COMMANDS_H
#define FRAME_PACER_HUD_VULKAN_COMMANDS_H

#include <stdbool.h>
#include <vulkan/vulkan.h>

enum frame_pacer_hud_command {
    FRAME_PACER_HUD_COMMAND_GET_SWAPCHAIN_IMAGES,
    FRAME_PACER_HUD_COMMAND_CREATE_IMAGE_VIEW,
    FRAME_PACER_HUD_COMMAND_DESTROY_IMAGE_VIEW,
    FRAME_PACER_HUD_COMMAND_CREATE_RENDER_PASS,
    FRAME_PACER_HUD_COMMAND_DESTROY_RENDER_PASS,
    FRAME_PACER_HUD_COMMAND_CREATE_FRAMEBUFFER,
    FRAME_PACER_HUD_COMMAND_DESTROY_FRAMEBUFFER,
    FRAME_PACER_HUD_COMMAND_CREATE_SHADER_MODULE,
    FRAME_PACER_HUD_COMMAND_DESTROY_SHADER_MODULE,
    FRAME_PACER_HUD_COMMAND_CREATE_PIPELINE_LAYOUT,
    FRAME_PACER_HUD_COMMAND_DESTROY_PIPELINE_LAYOUT,
    FRAME_PACER_HUD_COMMAND_CREATE_GRAPHICS_PIPELINES,
    FRAME_PACER_HUD_COMMAND_DESTROY_PIPELINE,
    FRAME_PACER_HUD_COMMAND_CREATE_COMMAND_POOL,
    FRAME_PACER_HUD_COMMAND_DESTROY_COMMAND_POOL,
    FRAME_PACER_HUD_COMMAND_ALLOCATE_COMMAND_BUFFERS,
    FRAME_PACER_HUD_COMMAND_CREATE_FENCE,
    FRAME_PACER_HUD_COMMAND_DESTROY_FENCE,
    FRAME_PACER_HUD_COMMAND_WAIT_FOR_FENCES,
    FRAME_PACER_HUD_COMMAND_RESET_FENCES,
    FRAME_PACER_HUD_COMMAND_CREATE_SEMAPHORE,
    FRAME_PACER_HUD_COMMAND_DESTROY_SEMAPHORE,
    FRAME_PACER_HUD_COMMAND_CREATE_BUFFER,
    FRAME_PACER_HUD_COMMAND_DESTROY_BUFFER,
    FRAME_PACER_HUD_COMMAND_ALLOCATE_MEMORY,
    FRAME_PACER_HUD_COMMAND_FREE_MEMORY,
    FRAME_PACER_HUD_COMMAND_MAP_MEMORY,
    FRAME_PACER_HUD_COMMAND_UNMAP_MEMORY,
    FRAME_PACER_HUD_COMMAND_BIND_BUFFER_MEMORY,
    FRAME_PACER_HUD_COMMAND_GET_BUFFER_MEMORY_REQUIREMENTS,
    FRAME_PACER_HUD_COMMAND_RESET_COMMAND_BUFFER,
    FRAME_PACER_HUD_COMMAND_BEGIN_COMMAND_BUFFER,
    FRAME_PACER_HUD_COMMAND_END_COMMAND_BUFFER,
    FRAME_PACER_HUD_COMMAND_PIPELINE_BARRIER,
    FRAME_PACER_HUD_COMMAND_BEGIN_RENDER_PASS,
    FRAME_PACER_HUD_COMMAND_END_RENDER_PASS,
    FRAME_PACER_HUD_COMMAND_BIND_PIPELINE,
    FRAME_PACER_HUD_COMMAND_BIND_VERTEX_BUFFERS,
    FRAME_PACER_HUD_COMMAND_DRAW,
    FRAME_PACER_HUD_COMMAND_QUEUE_SUBMIT,
    FRAME_PACER_HUD_COMMAND_SET_VIEWPORT,
    FRAME_PACER_HUD_COMMAND_SET_SCISSOR,
    FRAME_PACER_HUD_COMMAND_PUSH_CONSTANTS,
    FRAME_PACER_HUD_REQUIRED_COMMAND_COUNT,
};

struct frame_pacer_hud_commands {
    PFN_vkVoidFunction functions[FRAME_PACER_HUD_REQUIRED_COMMAND_COUNT];
};

bool frame_pacer_hud_resolve_commands(struct frame_pacer_hud_commands *,
                                      PFN_vkGetDeviceProcAddr, VkDevice);
const char *frame_pacer_hud_required_command_name(unsigned int index);

#endif
